SELECT 
    YEAR(T2.SALES_DATE) AS YEAR, 
    MONTH(T2.SALES_DATE) AS MONTH, 
    T1.GENDER AS GENDER,
    COUNT(DISTINCT T2.USER_ID) AS USERS
FROM USER_INFO AS T1
    INNER JOIN ONLINE_SALE AS T2 
        ON T1.USER_ID = T2.USER_ID
    WHERE GENDER IS NOT NULL
    GROUP BY YEAR, MONTH, GENDER
    ORDER BY YEAR, MONTH, GENDER;