SELECT 
        A.ANIMAL_ID
    ,   A.NAME
    # ,   B.DATETIME AS `IN`
    # ,   A.DATETIME AS `OUT`
    # ,   COUNT(*)
FROM ANIMAL_OUTS AS A
LEFT JOIN ANIMAL_INS AS B
    ON A.ANIMAL_ID = B.ANIMAL_ID
    WHERE B.DATETIME IS NULL
    ORDER BY A.ANIMAL_ID, A.NAME
