WITH recursive HOUR_TABLE AS (
    SELECT 0 AS `HOUR`, 0 AS `COUNT`
    UNION ALL
    SELECT `HOUR` + 1, 0
    FROM HOUR_TABLE
    WHERE `HOUR` < 23
)

SELECT T2.HOUR AS HOUR, IFNULL(T1.COUNT, T2.COUNT) AS COUNT FROM (
    SELECT 
        HOUR(DATETIME) AS HOUR, 
        COUNT(*) AS `COUNT` 
    FROM ANIMAL_OUTS
        GROUP BY HOUR
) AS T1
    RIGHT JOIN HOUR_TABLE AS T2 ON T1.HOUR = T2.HOUR
    ORDER BY HOUR
