WITH RARE_ITEMS AS (
    SELECT 
            ITEM_ID
    FROM    ITEM_INFO
    WHERE   RARITY LIKE 'RARE'
)

,   REINFORCED_ITEMS AS (
    SELECT
            B.ITEM_ID
    FROM    RARE_ITEMS  AS A
    JOIN    ITEM_TREE   AS B
            ON A.ITEM_ID = B.PARENT_ITEM_ID
)

SELECT
        A.ITEM_ID
    ,   B.ITEM_NAME
    ,   B.RARITY
FROM    REINFORCED_ITEMS    AS A
JOIN    ITEM_INFO           AS B
        ON A.ITEM_ID = B.ITEM_ID

ORDER
BY      A.ITEM_ID DESC