WITH MAXIMAS AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS `LENGTH` FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
)

SELECT A.ID, C.FISH_NAME, A.LENGTH FROM FISH_INFO AS A
    JOIN MAXIMAS AS B
    ON A.FISH_TYPE = B.FISH_TYPE AND A.LENGTH = B.LENGTH
    JOIN FISH_NAME_INFO AS C
    ON C.FISH_TYPE = A.FISH_TYPE
    ORDER BY A.ID ASC
    